// Generated by Wrangler by running `wrangler types`

interface Env {
	OPENAI_API_KEY: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	Chat: DurableObjectNamespace<import("./server/server").Chat>;
}
